# Generated by Django 2.2.4 on 2019-08-22 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='ip',
            field=models.CharField(max_length=500),
        ),
    ]
