# Generated by Django 2.2.4 on 2019-08-22 18:28

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190822_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=2000)),
                ('step_1', models.CharField(max_length=2000)),
                ('step_2', models.CharField(max_length=2000)),
                ('step_3', models.CharField(max_length=2000)),
                ('step_4', models.CharField(max_length=10)),
                ('step_5', models.CharField(max_length=250)),
                ('step_6', models.IntegerField(max_length=12)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
