# Generated by Django 2.2.4 on 2019-08-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='step_6',
            field=models.IntegerField(),
        ),
    ]
