# Generated by Django 2.2.4 on 2019-08-28 13:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190822_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choises', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Кому вы должны'), ('2', 'Сколько вы должны')], default='1', max_length=1), size=None)),
            ],
        ),
    ]
