# Generated by Django 2.2.4 on 2019-08-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190829_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='description',
            field=models.CharField(max_length=300, verbose_name='description'),
        ),
    ]
