# Generated by Django 2.2.4 on 2019-08-28 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190829_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300, null=True, verbose_name='description')),
            ],
        ),
        migrations.RemoveField(
            model_name='choices',
            name='description',
        ),
        migrations.AddField(
            model_name='choices',
            name='choice_text',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='answer1',
            name='answer_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Question'),
        ),
        migrations.AddField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Question'),
        ),
    ]
