# Generated by Django 2.2.4 on 2019-08-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190829_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Answer1',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
