# Generated by Django 2.2.4 on 2019-08-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_choice_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='step_1',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='step_2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='step_3',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='step_4',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='step_5',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='step_6',
        ),
        migrations.AddField(
            model_name='answer',
            name='choices',
            field=models.ManyToManyField(to='blog.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='questions',
            field=models.ManyToManyField(to='blog.Question'),
        ),
    ]
