# Generated by Django 2.2.4 on 2019-08-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190829_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Имя'),
        ),
    ]
