# Generated by Django 2.2.4 on 2019-08-29 18:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190829_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='komu',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Банкам', 'Банкам'), ('Часным лица', 'Часным лица'), ('Судебным приставам', 'Судебным приставам'), ('Микрофинансовым организациям', 'Микрофинансовым организациям'), ('Другое', 'Другое')], max_length=73, verbose_name='Кому Вы должны ?'),
        ),
    ]
