# Generated by Django 2.2.4 on 2019-08-29 18:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190829_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='prosrochky',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Нет'), (2, 'Да, до месяца'), (1, 'Да, от месяца до трёх'), (1, 'Более трёх месяцев')], max_length=7, verbose_name='Есть ли у Вас просрочки по кредитам ?'),
        ),
    ]
