# Generated by Django 2.2.4 on 2019-09-01 17:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20190901_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='author_ip',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Как Вас зовут ?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Введите ваш телефон'),
        ),
    ]
