# Generated by Django 2.2.4 on 2019-09-02 23:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_choise_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
        migrations.AlterField(
            model_name='question',
            name='pud_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 23, 1, 52, 675479, tzinfo=utc), verbose_name='date_published'),
        ),
    ]
