# Generated by Django 2.2.4 on 2019-09-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20190903_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pud_date',
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date_published'),
        ),
    ]
