# Generated by Django 2.2.4 on 2019-09-07 08:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20190907_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='komu',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Банкам', 'Банкам'), ('Часным лица', 'Часным лица'), ('Судебным приставам', 'Судебным приставам'), ('Микрофинансовым организациям', 'Микрофинансовым организациям'), ('Другое', 'Другое')], help_text='custom-control-label', max_length=73, verbose_name='Кому Вы должны ?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='zalogi',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Есть'), (2, 'Нет')], help_text=' Например, ипотечная квартира или автомобиль купленный в автокредит.', max_length=3, verbose_name='Есть ли у Вас имущество в залоге ?'),
        ),
    ]
