# Generated by Django 2.2.4 on 2019-09-23 13:47

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20190919_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='komu',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Банкам', 'Банкам'), ('Часным', 'Часным лица'), ('Приставам', 'Судебным приставам'), ('Микрофинансам', 'Микрофинансовым организациям'), ('Другое', 'Другое')], error_messages={'invalid_list': 'Введите список значений.', 'required': 'Обязательное поле.'}, help_text='Выберете 1 или более вариантов.', max_length=44, verbose_name='Кому Вы должны ?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(default='', error_messages={'required': 'Обязательное поле.'}, help_text='Представьтесь пожалуйста,              нам необходимо знать Ваше имя или псевдоним', max_length=200, verbose_name='Как Вас зовут ?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'required': 'Обязательное поле.'}, help_text='Введите Ваш номер телефона', max_length=128, region=None, verbose_name='Вот и последний шаг.'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='prosrochky',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Нет'), (2, 'Да, до месяца'), (1, 'Да, от месяца до трёх'), (1, 'Более трёх месяцев')], error_messages={'required': 'Обязательное поле.'}, help_text='Или любым другим платежам срок по которым уже наступил.', max_length=7, verbose_name='Есть ли у Вас просрочки по кредитам ?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='skolko',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'До 200 000 руб'), (2, 'От 200 000 руб до 500 000 руб'), (3, 'От 500 000 руб до 1 000 000 руб'), (4, 'Более 1 000 000 руб'), (5, 'Более 5 000 000 руб')], error_messages={'required': 'Обязательное поле.'}, help_text='Укажите пожалуйста приблизительный диапазон', max_length=9, verbose_name='Сколько всего Вы должны ?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='zalogi',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Есть'), (2, 'Нет')], error_messages={'required': 'Обязательное поле.'}, help_text='Например, ипотечная квартира или             автомобиль купленный в автокредит.', max_length=3, verbose_name='Есть ли у Вас имущество в залоге ?'),
        ),
    ]
