# Generated by Django 2.2.4 on 2019-09-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20190923_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['author', '-created_time']},
        ),
    ]
