# Generated by Django 2.2.4 on 2019-09-23 15:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20190923_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='prosrochky',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Нет', 'Нет'), ('Да, до месяца', 'Да, до месяца'), ('Да, от месяца до трёх', 'Да, от месяца до трёх'), ('Более трёх месяцев', 'Более трёх месяцев')], error_messages={'required': 'Обязательное поле.'}, help_text='Или любым другим платежам срок по которым уже наступил.', max_length=58, verbose_name='Есть ли у Вас просрочки по кредитам ?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='zalogi',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Есть', 'Есть'), ('Нет', 'Нет')], error_messages={'required': 'Обязательное поле.'}, help_text='Например, ипотечная квартира или             автомобиль купленный в автокредит.', max_length=8, verbose_name='Есть ли у Вас имущество в залоге ?'),
        ),
    ]
