# Generated by Django 2.2.4 on 2019-09-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20190923_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_time']},
        ),
    ]
