# Generated by Django 2.2.4 on 2019-09-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('html', models.TextField()),
                ('text_en', models.TextField()),
                ('text_ru', models.TextField()),
                ('pubdate', models.DateField(auto_now_add=True)),
                ('rewritedate', models.DateField(auto_now=True)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curiosity.Channel')),
                ('tags', models.ManyToManyField(to='curiosity.Tag')),
            ],
            options={
                'ordering': ['title', '-pubdate'],
            },
        ),
    ]
