# Generated by Django 2.2.4 on 2019-09-23 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0002_auto_20190923_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curiosity.Channel', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='post',
            name='html',
            field=models.TextField(verbose_name='ХТМЛ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rewritedate',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='curiosity.Tag', verbose_name='Хештеги'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_en',
            field=models.TextField(verbose_name='Английский текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_ru',
            field=models.TextField(verbose_name='Русский текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Заголовок'),
        ),
    ]
