# Generated by Django 2.2.4 on 2019-09-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0003_auto_20190923_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_ru',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_en',
        ),
    ]
