# Generated by Django 2.2.4 on 2019-09-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0007_auto_20190924_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='curiosity/static/curiosity/img/', verbose_name='Изображение'),
        ),
    ]
