# Generated by Django 2.2.4 on 2019-09-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0009_auto_20190925_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pubdate']},
        ),
    ]
