# Generated by Django 2.2.4 on 2019-10-01 14:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0011_auto_20191001_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='original_post',
            field=models.URLField(null=True, verbose_name='Источник'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7cb720ad-f8fe-413f-8c0a-c60ecfe08ec2'), primary_key=True, serialize=False)),
                ('url_500x300', models.URLField(max_length=1500, verbose_name='500x300')),
                ('url_750x600', models.URLField(max_length=1500, verbose_name='750x600')),
                ('url_2800x600', models.URLField(max_length=1500, verbose_name='2800x600')),
                ('role', models.CharField(blank=True, choices=[('о', 'Обложка'), ('б1', 'Блок 1'), ('б2', 'Блок 2'), ('б3', 'Блок 3')], default='о', max_length=2)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curiosity.Post', verbose_name='Изображение')),
            ],
            options={
                'ordering': ['post'],
            },
        ),
    ]
