# Generated by Django 2.2.4 on 2019-10-01 16:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0012_auto_20191001_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['created_time']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='role',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url_2800x600',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url_500x300',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url_750x600',
        ),
        migrations.AddField(
            model_name='image',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='image',
            name='urls_x300',
            field=models.TextField(default=None, null=True, verbose_name='x300'),
        ),
        migrations.AddField(
            model_name='image',
            name='urls_x600',
            field=models.TextField(default=None, null=True, verbose_name='x600'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a935715-f544-434f-8d92-c90ee35fb8b9'), primary_key=True, serialize=False),
        ),
    ]
