# Generated by Django 2.2.4 on 2019-10-01 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0013_auto_20191001_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='role',
            field=models.CharField(blank=True, choices=[('о', 'Обложка'), ('б1', 'Блок 1'), ('б2', 'Блок 2'), ('б3', 'Блок 3')], default='о', max_length=2, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10df653b-150b-498e-8aaf-e67285888b78'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curiosity.Post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='image',
            name='urls_x300',
            field=models.TextField(default=None, null=True, verbose_name='Размеры x300'),
        ),
        migrations.AlterField(
            model_name='image',
            name='urls_x600',
            field=models.TextField(default=None, null=True, verbose_name='Размеры x600'),
        ),
    ]
