# Generated by Django 2.2.4 on 2019-10-01 18:06

import django.core.files.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0014_auto_20191001_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e8bde87d-20a6-4857-a808-43b64e58e01a'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='d:/media'), upload_to='', verbose_name='Изображение'),
        ),
    ]
