# Generated by Django 2.2.4 on 2019-10-01 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0015_auto_20191001_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d268c1ca-149b-4c57-9b5b-83b1316845de'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=500, unique=True, verbose_name='Заголовок'),
        ),
    ]
