# Generated by Django 2.2.4 on 2019-10-01 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0016_auto_20191001_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('547a6a8b-6c4a-44d2-b2d9-029a21d58606'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
