# Generated by Django 2.2.4 on 2019-10-02 06:34

import django.core.files.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0017_auto_20191001_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d89bd06a-6df7-4a33-bca8-d65ae075c9c6'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to='', verbose_name='Изображение'),
        ),
    ]
