# Generated by Django 2.2.4 on 2019-10-02 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0018_auto_20191002_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('403f3c04-23aa-4e7d-b910-6bc8c9c470cf'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
