# Generated by Django 2.2.4 on 2019-10-02 07:32

import django.core.files.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0019_auto_20191002_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6bf16139-ddef-4df6-b8f7-08447feb96d2'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='d:/media'), upload_to='', verbose_name='Изображение'),
        ),
    ]
