# Generated by Django 2.2.4 on 2019-10-02 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0020_auto_20191002_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c7d2420-92c2-4653-8e90-f115809af84e'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
