# Generated by Django 2.2.4 on 2019-10-02 16:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0022_auto_20191002_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('54ccf95c-f14d-4563-9e1f-f4dbfa6135d8'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
