# Generated by Django 2.2.4 on 2019-10-02 17:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0023_auto_20191002_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url_prefix',
            field=models.CharField(default='https://dw8stlw9qt0iz.cloudfront.net/', max_length=37, verbose_name='Префикс'),
        ),
        migrations.AddField(
            model_name='image',
            name='url_sufix',
            field=models.CharField(default='.png', max_length=37, verbose_name='Суфикс'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c469fb6b-8c17-4bf1-ba31-62baac9a4e68'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
