# Generated by Django 2.2.4 on 2019-10-02 17:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0024_auto_20191002_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2d1d74db-933d-4644-b34e-560163aa1033'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url_sufix',
            field=models.CharField(default='.png', max_length=4, verbose_name='Суфикс'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curiosity.Image', verbose_name='Первое изображение'),
        ),
    ]
