# Generated by Django 2.2.4 on 2019-10-02 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0025_auto_20191002_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4d80fee7-838b-4884-b80a-d45c54cf1d35'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
