# Generated by Django 2.2.4 on 2019-10-02 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0026_auto_20191002_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d7aa1fb1-c749-49be-9a20-eb00710aeb29'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
