# Generated by Django 2.2.4 on 2019-10-03 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0027_auto_20191002_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7296a7d4-0709-418c-849e-2835587aaae7'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
