# Generated by Django 2.2.4 on 2019-10-04 02:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0028_auto_20191004_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97ffb364-7240-41e8-84d9-adba046c39e7'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
