# Generated by Django 2.2.4 on 2019-10-06 14:41

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0029_auto_20191004_0552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rewritedate',
            new_name='rewrite_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pubdate',
        ),
        migrations.AddField(
            model_name='channel',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Даты создания'),
        ),
        migrations.AddField(
            model_name='channel',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайк'),
        ),
        migrations.AddField(
            model_name='channel',
            name='name_en',
            field=models.CharField(null=True, max_length=250, unique=True, verbose_name='Английское название'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата обнаружения'),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Обнаружен', 'FINDED'), ('Опубликован', 'PUBLISHED')], default='Создан', max_length=15, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Даты создания'),
        ),
        migrations.AddField(
            model_name='tag',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайк'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(null=True, max_length=250, unique=True, verbose_name='Английское название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(null=True, max_length=250, unique=True, verbose_name='Русское название'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93d5c882-f6c3-41e3-b8f9-3b6becaa22fd'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='html',
            field=models.TextField(null=True, verbose_name='ХТМЛ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(null=True, verbose_name='Русский текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=500, null=True, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Русское название'),
        ),
    ]
