# Generated by Django 2.2.4 on 2019-10-06 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0030_auto_20191006_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(null=True, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Русское название'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name_en',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Английское название'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a1a33544-37e9-462c-ba98-c63b50b36694'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
