# Generated by Django 2.2.4 on 2019-10-07 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0032_auto_20191006_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, null=True, verbose_name='Текст')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6777414b-8cc3-4759-ab38-0e95dc103339'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Обнаружен', 'FINDED'), ('Опубликован', 'PUBLISHED')], default='Обнаружен', max_length=15, verbose_name='Статус'),
        ),
    ]
