# Generated by Django 2.2.4 on 2019-10-08 04:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0035_auto_20191008_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9dc0f918-81de-4aa8-95ea-50ab7299741d'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
