# Generated by Django 2.2.4 on 2019-10-08 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0036_auto_20191008_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1bd5f8ce-b98f-4219-8728-1ed802ecdcf3'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
