# Generated by Django 2.2.4 on 2019-10-08 15:51

from django.db import migrations, models
import re
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0037_auto_20191008_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='PATH_MY_HREF',
            field=models.CharField(default='D:\\Projects\\py\\myblog-development\\curiosityworker/my_href.db', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='PATH_TO_BACKUP_HREF',
            field=models.CharField(default='D:\\Projects\\py\\myblog-development\\curiosityworker/my_href_backup.db', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='PATH_TO_FONTS',
            field=models.CharField(default='D:\\Projects\\py\\myblog-development\\curiosityworker/topics/Roboto-Fonts/Roboto-Bold.ttf', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='PATH_TO_IMG_BUTTON',
            field=models.CharField(default='D:\\Projects\\py\\myblog-development\\curiosityworker/Button.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='PATH_TO_IMG_LOGO_PAINTER',
            field=models.CharField(default='D:\\Projects\\py\\myblog-development\\curiosityworker/desing/logo-painter.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='PATH_TO_IMG_ORIGINAL',
            field=models.CharField(default='D:\\Projects\\py\\myblog-development\\curiosityworker/topics/IMG_ORIGINAL.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='PATH_TO_IMG_RESIZE',
            field=models.CharField(default='D:\\Projects\\py\\myblog-development\\curiosityworker/topics/IMG_RESIZE.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='PATH_TO_LOG',
            field=models.CharField(default='D:\\Projects\\py\\myblog-development\\curiosityworker/curiosity-to-vk.log', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='PATH_TO_POST',
            field=models.CharField(default='D:\\Projects\\py\\myblog-development\\curiosityworker/href-to-post.db', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='UUID4_HEX_REGEX',
            field=models.CharField(default=re.compile('[0-9a-f]{12}4[0-9a-f]{3}[89ab][0-9a-f]{15}\\Z', 2), max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='VK_GROUP_ID',
            field=models.CharField(default=181925964, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='VK_TOKEN',
            field=models.CharField(default='9bfae56722ff872d603c6b0aa10c9c47f42fa00de836de4e47217e44c7f06259767efb6ee95c494303a8e', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Английский текст'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=500, null=True, unique=True, verbose_name='Английский аголовок'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d658bd28-7bcf-4636-9b21-c835470d9f53'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
