# Generated by Django 2.2.4 on 2019-10-08 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0039_auto_20191008_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='PATH_TO_POST',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e66222ae-2ab4-4c24-a267-8d64dc5d4ad4'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
