# Generated by Django 2.2.4 on 2019-10-08 22:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0040_auto_20191008_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='PATH_MY_HREF',
        ),
        migrations.RemoveField(
            model_name='post',
            name='PATH_TO_BACKUP_HREF',
        ),
        migrations.RemoveField(
            model_name='post',
            name='PATH_TO_FONTS',
        ),
        migrations.RemoveField(
            model_name='post',
            name='PATH_TO_IMG_BUTTON',
        ),
        migrations.RemoveField(
            model_name='post',
            name='PATH_TO_IMG_LOGO_PAINTER',
        ),
        migrations.RemoveField(
            model_name='post',
            name='PATH_TO_IMG_ORIGINAL',
        ),
        migrations.RemoveField(
            model_name='post',
            name='PATH_TO_IMG_RESIZE',
        ),
        migrations.RemoveField(
            model_name='post',
            name='PATH_TO_LOG',
        ),
        migrations.RemoveField(
            model_name='post',
            name='UUID4_HEX_REGEX',
        ),
        migrations.RemoveField(
            model_name='post',
            name='VK_GROUP_ID',
        ),
        migrations.RemoveField(
            model_name='post',
            name='VK_TOKEN',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3bc34c75-dbf6-49e7-a81a-9a3b0853757b'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
