# Generated by Django 2.2.4 on 2019-10-09 22:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0042_auto_20191009_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date'], 'permissions': (('can_auto_parse_posts', 'Автоматически парсить посты'),)},
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5544f271-5c60-4987-8f3d-a31d9bed0200'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
