# Generated by Django 2.2.4 on 2019-10-10 00:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0044_auto_20191010_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('091e2901-7f0e-41c5-b611-a71d2b3ba2a8'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
