# Generated by Django 2.2.4 on 2019-10-10 05:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0046_auto_20191010_0532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date'], 'permissions': (('can_auto_parse_posts', 'Auto parse post'),)},
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2570e68a-d9fc-462f-9cc1-c448e392381f'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
