# Generated by Django 2.2.4 on 2019-10-10 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0047_auto_20191010_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('76163d8c-4e09-4c8f-854c-eb35530447c8'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
