# Generated by Django 2.2.4 on 2019-10-10 06:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0048_auto_20191010_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('529f3b42-ba92-4145-a552-c3d01a154b37'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
