# Generated by Django 2.2.4 on 2019-10-10 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0050_auto_20191010_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f297b1ba-6d2a-45f8-84ca-53cdbac1b6b8'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
