# Generated by Django 2.2.6 on 2019-10-10 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0051_auto_20191010_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date'], 'permissions': (('can_mark_returned', 'Can mark returned'),)},
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1b0c881b-92d2-4082-b76c-bd0835900be4'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
